/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package m.MDSUI;

import java.awt.Component;
import java.awt.Font;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Bogdan
 */
public class MDSUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MDSUI.class.getName());

    /**
     * Creates new form MDSUI
     */
    public MDSUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Tab_Schedule = new javax.swing.JPanel();
        Table_Schedule1 = new javax.swing.JScrollPane();
        Table_Schedule = new javax.swing.JTable();
        Label_Schedule = new javax.swing.JLabel();
        Tab_Account = new javax.swing.JPanel();
        Label_Username = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        Label_Email = new javax.swing.JLabel();
        Button_ChangePass = new javax.swing.JButton();
        Label_HoursLearning = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        Button_DeleteAcc = new javax.swing.JButton();
        Btn_LogIn = new javax.swing.JButton();
        Btn_ChangeAcc = new javax.swing.JButton();
        Btn_LogOut = new javax.swing.JButton();
        txtParola = new javax.swing.JPasswordField();
        txtOre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmboNivel = new javax.swing.JComboBox<>();
        Tab_Settings = new javax.swing.JPanel();
        Label_ChangeFont = new javax.swing.JLabel();
        ComBox_Fonts = new javax.swing.JComboBox<>();
        Label_ChangeFont1 = new javax.swing.JLabel();
        ComBox_UIsize = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ComBox_Theme = new javax.swing.JComboBox<>();
        Tab_News = new javax.swing.JPanel();
        Label_News = new javax.swing.JLabel();
        Panel_News = new javax.swing.JPanel();
        TextBox_News = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Label_Recommend = new javax.swing.JLabel();
        Panel_Recommend = new javax.swing.JPanel();
        TextBox_Recommend = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(68, 86, 98));
        jPanel1.setForeground(new java.awt.Color(167, 21, 21));

        Tab_Schedule.setForeground(new java.awt.Color(44, 49, 57));

        Table_Schedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"
            }
        ));
        Table_Schedule1.setViewportView(Table_Schedule);

        Label_Schedule.setText("Schedule");

        javax.swing.GroupLayout Tab_ScheduleLayout = new javax.swing.GroupLayout(Tab_Schedule);
        Tab_Schedule.setLayout(Tab_ScheduleLayout);
        Tab_ScheduleLayout.setHorizontalGroup(
            Tab_ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tab_ScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Table_Schedule1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tab_ScheduleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_Schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );
        Tab_ScheduleLayout.setVerticalGroup(
            Tab_ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tab_ScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Schedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Table_Schedule1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Schedule", Tab_Schedule);

        Label_Username.setText("Username:");

        txtUsername.addActionListener(this::txtUsernameActionPerformed);

        Label_Email.setText("Email:");

        Button_ChangePass.setText("Change Password");
        Button_ChangePass.addActionListener(this::Button_ChangePassActionPerformed);

        Label_HoursLearning.setText("Password:");

        btnSave.setText("Create Account");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        Button_DeleteAcc.setText("Delete Account");
        Button_DeleteAcc.addActionListener(this::Button_DeleteAccActionPerformed);

        Btn_LogIn.setText("Log In");
        Btn_LogIn.addActionListener(this::Btn_LogInActionPerformed);

        Btn_ChangeAcc.setText("Change Account");
        Btn_ChangeAcc.addActionListener(this::Btn_ChangeAccActionPerformed);

        Btn_LogOut.setText("Log Out");
        Btn_LogOut.addActionListener(this::Btn_LogOutActionPerformed);

        txtOre.addActionListener(this::txtOreActionPerformed);

        jLabel1.setText("Numar de ore:");

        jLabel3.setText("Nivel cunostinte:");

        cmboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Incepator", "Intermediar", "Avansat" }));
        cmboNivel.addActionListener(this::cmboNivelActionPerformed);

        javax.swing.GroupLayout Tab_AccountLayout = new javax.swing.GroupLayout(Tab_Account);
        Tab_Account.setLayout(Tab_AccountLayout);
        Tab_AccountLayout.setHorizontalGroup(
            Tab_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_AccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Tab_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_HoursLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(Tab_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab_AccountLayout.createSequentialGroup()
                        .addComponent(txtParola, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_ChangePass)
                        .addContainerGap())
                    .addGroup(Tab_AccountLayout.createSequentialGroup()
                        .addGroup(Tab_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(txtUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(Tab_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(Tab_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOre)
                            .addComponent(cmboNivel, 0, 111, Short.MAX_VALUE))
                        .addGap(164, 164, 164))))
            .addGroup(Tab_AccountLayout.createSequentialGroup()
                .addGroup(Tab_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_DeleteAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_LogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_ChangeAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Tab_AccountLayout.setVerticalGroup(
            Tab_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_AccountLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(Tab_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Username)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Tab_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Tab_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_HoursLearning)
                    .addComponent(txtParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_ChangePass))
                .addGap(28, 28, 28)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_LogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_ChangeAcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_LogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(Button_DeleteAcc)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Account", Tab_Account);

        Label_ChangeFont.setText("Change Text Font:");

        ComBox_Fonts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segoe UI", "Serif", "Comic Sans MS", "Cracked" }));
        ComBox_Fonts.addActionListener(this::ComBox_FontsActionPerformed);

        Label_ChangeFont1.setText("Interface size:");

        ComBox_UIsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "small", "medium", "large" }));
        ComBox_UIsize.addActionListener(this::ComBox_UIsizeActionPerformed);

        jLabel2.setText("Change Theme:");

        ComBox_Theme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Windows", "Nimbus", "Metal" }));
        ComBox_Theme.addActionListener(this::ComBox_ThemeActionPerformed);

        javax.swing.GroupLayout Tab_SettingsLayout = new javax.swing.GroupLayout(Tab_Settings);
        Tab_Settings.setLayout(Tab_SettingsLayout);
        Tab_SettingsLayout.setHorizontalGroup(
            Tab_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_SettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Tab_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Label_ChangeFont, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_ChangeFont1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addGroup(Tab_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComBox_UIsize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComBox_Theme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComBox_Fonts, 0, 333, Short.MAX_VALUE))
                .addContainerGap())
        );
        Tab_SettingsLayout.setVerticalGroup(
            Tab_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_SettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Tab_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ChangeFont)
                    .addComponent(ComBox_Fonts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Tab_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ChangeFont1)
                    .addComponent(ComBox_UIsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Tab_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComBox_Theme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(304, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Settings", Tab_Settings);

        Label_News.setText("News:");

        Panel_News.setBackground(new java.awt.Color(46, 63, 75));
        Panel_News.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(117, 141, 178), 2, true));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        TextBox_News.setViewportView(jTextArea1);

        javax.swing.GroupLayout Panel_NewsLayout = new javax.swing.GroupLayout(Panel_News);
        Panel_News.setLayout(Panel_NewsLayout);
        Panel_NewsLayout.setHorizontalGroup(
            Panel_NewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextBox_News)
                .addContainerGap())
        );
        Panel_NewsLayout.setVerticalGroup(
            Panel_NewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextBox_News, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        Label_Recommend.setText("Recommendations:");

        Panel_Recommend.setBackground(new java.awt.Color(46, 63, 75));
        Panel_Recommend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(117, 141, 178), 2, true));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        TextBox_Recommend.setViewportView(jTextArea2);

        javax.swing.GroupLayout Panel_RecommendLayout = new javax.swing.GroupLayout(Panel_Recommend);
        Panel_Recommend.setLayout(Panel_RecommendLayout);
        Panel_RecommendLayout.setHorizontalGroup(
            Panel_RecommendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RecommendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextBox_Recommend, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_RecommendLayout.setVerticalGroup(
            Panel_RecommendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RecommendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextBox_Recommend, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Tab_NewsLayout = new javax.swing.GroupLayout(Tab_News);
        Tab_News.setLayout(Tab_NewsLayout);
        Tab_NewsLayout.setHorizontalGroup(
            Tab_NewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_NewsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Tab_NewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab_NewsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Tab_NewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Panel_Recommend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Panel_News, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Tab_NewsLayout.createSequentialGroup()
                        .addGroup(Tab_NewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_News, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Recommend))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Tab_NewsLayout.setVerticalGroup(
            Tab_NewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_NewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_News)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_News, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Recommend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Recommend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("News & Recommendations", Tab_News);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int fontSize=12;

    private void ComBox_ThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBox_ThemeActionPerformed
        // TODO add your handling code here:
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (ComBox_Theme.getSelectedItem().toString().equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    UIManager.setLookAndFeel(info.getClassName());
                    Component[] Tabs=jPanel1.getComponents();
                    Component[] UInews=Tab_News.getComponents();
                    Component[] UIsettings=Tab_Settings.getComponents();
                    Component[] UIaccount=Tab_Account.getComponents();
                    Component[] UIschedule=Tab_Schedule.getComponents();
                    Component[] UItable=Table_Schedule1.getComponents();

                    for(Component c : UIsettings){
                        SwingUtilities.updateComponentTreeUI(c);
                    }

                    for(Component c : Tabs){
                        SwingUtilities.updateComponentTreeUI(c);
                    }

                    for(Component c : UInews){
                        SwingUtilities.updateComponentTreeUI(c);
                    }

                    for(Component c : UIaccount){
                        SwingUtilities.updateComponentTreeUI(c);
                    }

                    for(Component c : UIschedule){
                        SwingUtilities.updateComponentTreeUI(c);
                    }

                    for(Component c : UItable){
                        SwingUtilities.updateComponentTreeUI(c);
                    }

                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComBox_ThemeActionPerformed

    private void ComBox_UIsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBox_UIsizeActionPerformed
        // TODO add your handling code here:
        if(ComBox_UIsize.getSelectedItem().toString().equals("small")){
            fontSize=12;
        }else if(ComBox_UIsize.getSelectedItem().toString().equals("medium")){
            fontSize=16;
        } else if(ComBox_UIsize.getSelectedItem().toString().equals("large")){
            fontSize=20;
        }else{
            fontSize=12;
        }
        Font f=new Font(ComBox_Fonts.getSelectedItem().toString(), Font.PLAIN, fontSize);
        Component[] Tabs=jPanel1.getComponents();
        Component[] UInews=Tab_News.getComponents();
        Component[] UIsettings=Tab_Settings.getComponents();
        Component[] UIaccount=Tab_Account.getComponents();
        Component[] UIschedule=Tab_Schedule.getComponents();
        Component[] UItable=Table_Schedule1.getComponents();

        for(Component comp : UIsettings){
            comp.setFont(f);
        }

        for(Component comp : Tabs){
            comp.setFont(f);
        }

        for(Component comp : UItable){
            comp.setFont(f);
        }

        for(Component comp : UIschedule){
            comp.setFont(f);
        }

        for(Component comp : UIaccount){
            comp.setFont(f);
        }

        for(Component comp : UInews){
            comp.setFont(f);
        }
    }//GEN-LAST:event_ComBox_UIsizeActionPerformed

    private void ComBox_FontsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBox_FontsActionPerformed
        // TODO add your handling code here:

        Font f=new Font(ComBox_Fonts.getSelectedItem().toString(), Font.PLAIN, 12);
        Component[] Tabs=jPanel1.getComponents();
        Component[] UInews=Tab_News.getComponents();
        Component[] UIsettings=Tab_Settings.getComponents();
        Component[] UIaccount=Tab_Account.getComponents();
        Component[] UIschedule=Tab_Schedule.getComponents();
        Component[] UItable=Table_Schedule1.getComponents();

        for(Component comp : UIsettings){
            comp.setFont(f);
        }

        for(Component comp : Tabs){
            comp.setFont(f);
        }

        for(Component comp : UItable){
            comp.setFont(f);
        }

        for(Component comp : UIschedule){
            comp.setFont(f);
        }

        for(Component comp : UIaccount){
            comp.setFont(f);
        }

        for(Component comp : UInews){
            comp.setFont(f);
        }
    }//GEN-LAST:event_ComBox_FontsActionPerformed

    private void Btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_LogOutActionPerformed

    private void Btn_ChangeAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ChangeAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ChangeAccActionPerformed

    private void Btn_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_LogInActionPerformed

    private void Button_DeleteAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteAccActionPerformed
 String email = txtEmail.getText().trim();
    String parola = new String(txtParola.getPassword());
    
    if (email.isEmpty() || parola.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Completează email-ul și parola pentru a confirma ștergerea!",
            "Atenție", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // dialog de confirmare - acțiune destructivă
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Esti sigur?\n" +
        "Aceasta actiune este IREVERSIBILA,\n" +
        "vor fi sterse toate sesiunile de studiu si competentele asociate.",
        "Confirmare stergere cont",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.WARNING_MESSAGE);
    
    if (confirm != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }
    
    new javax.swing.SwingWorker<String, Void>() {
        @Override
        protected String doInBackground() throws Exception {
            ApiService api = new ApiService();
            return api.deleteAccount(email, parola);
        }
        
        @Override
        protected void done() {
            try {
                get();
                javax.swing.JOptionPane.showMessageDialog(null,
                    "Cont sters!");
                txtUsername.setText("");
                txtEmail.setText("");
                txtParola.setText("");
                txtOre.setText("");
                cmboNivel.setSelectedIndex(0);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null,
                    "Eroare: " + ex.getCause().getMessage(),
                    "Eroare", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }.execute();
    }//GEN-LAST:event_Button_DeleteAccActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    String nume = txtUsername.getText().trim();
    String email = txtEmail.getText().trim();
    String parola = new String(txtParola.getPassword());
    String oreText = txtOre.getText().trim();
    String nivelText = (String) cmboNivel.getSelectedItem();
    
    if (nume.isEmpty() || email.isEmpty() || parola.isEmpty() || oreText.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Completeaza toate campurile!",
            "Atentie!!!", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    int ore;
    try {
        ore = Integer.parseInt(oreText);
        if (ore < 1 || ore > 24) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Numarul de ore trebuie sa fie intre 1 si 24!",
                "Atentie!!!", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Numarul de ore trebuie sa fie un numar intreg!",
            "Atentie!!!", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    int nivel;
    switch (nivelText) {
        case "Incepator":   nivel = 1; break;
        case "Intermediar": nivel = 2; break;
        case "Avansat":     nivel = 3; break;
        default:            nivel = 1;
    }
    
    final int nivelFinal = nivel;
    final int oreFinal = ore;
    
    new javax.swing.SwingWorker<String, Void>() {
        @Override
        protected String doInBackground() throws Exception {
            ApiService api = new ApiService();
            return api.createAccount(nume, email, parola, nivelFinal, oreFinal);
        }
        
        @Override
        protected void done() {
            try {
                get();
                javax.swing.JOptionPane.showMessageDialog(null,
                    "Cont creat cu succes!");
                txtUsername.setText("");
                txtEmail.setText("");
                txtParola.setText("");
                txtOre.setText("");
                cmboNivel.setSelectedIndex(0);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null,
                    "Eroare: " + ex.getCause().getMessage(),
                    "Eroare", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }.execute();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void Button_ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ChangePassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_ChangePassActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtOreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOreActionPerformed

    private void cmboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboNivelActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MDSUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ChangeAcc;
    private javax.swing.JButton Btn_LogIn;
    private javax.swing.JButton Btn_LogOut;
    private javax.swing.JButton Button_ChangePass;
    private javax.swing.JButton Button_DeleteAcc;
    private javax.swing.JComboBox<String> ComBox_Fonts;
    private javax.swing.JComboBox<String> ComBox_Theme;
    private javax.swing.JComboBox<String> ComBox_UIsize;
    private javax.swing.JLabel Label_ChangeFont;
    private javax.swing.JLabel Label_ChangeFont1;
    private javax.swing.JLabel Label_Email;
    private javax.swing.JLabel Label_HoursLearning;
    private javax.swing.JLabel Label_News;
    private javax.swing.JLabel Label_Recommend;
    private javax.swing.JLabel Label_Schedule;
    private javax.swing.JLabel Label_Username;
    private javax.swing.JPanel Panel_News;
    private javax.swing.JPanel Panel_Recommend;
    private javax.swing.JPanel Tab_Account;
    private javax.swing.JPanel Tab_News;
    private javax.swing.JPanel Tab_Schedule;
    private javax.swing.JPanel Tab_Settings;
    private javax.swing.JTable Table_Schedule;
    private javax.swing.JScrollPane Table_Schedule1;
    private javax.swing.JScrollPane TextBox_News;
    private javax.swing.JScrollPane TextBox_Recommend;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmboNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOre;
    private javax.swing.JPasswordField txtParola;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
