DROP TABLE UTILIZATORI CASCADE CONSTRAINTS;
DROP TABLE SESIUNI_STUDIU CASCADE CONSTRAINTS;
DROP TABLE PROGRAM_SAPTAMANAL CASCADE CONSTRAINTS;
DROP TABLE COMPETENTE CASCADE CONSTRAINTS;

CREATE TABLE UTILIZATORI (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PAROLA VARCHAR2(100),
    NIVEL_CUNOSTINTE VARCHAR2(50),  --folosit de ai pt estimari precise
    ORE_DISPONIBILE_ZI INTEGER
);

CREATE TABLE SESIUNI_STUDIU (  --istoric
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    DATA_SESIUNE DATE NOT NULL,
    MATERIE VARCHAR2(100) NOT NULL,
    DURATA_MINUTE INTEGER NOT NULL,
    CONSTRAINT fk_utilizator_sesiuni FOREIGN KEY (USER_ID) REFERENCES UTILIZATORI(ID)
);

CREATE TABLE PROGRAM_SAPTAMANAL (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    ZI DATE NOT NULL,
    MATERIE VARCHAR2(100) NOT NULL,
    DURATA_RECOMANDATA INTEGER,
    EDITAT_MANUAL NUMBER(1) DEFAULT 0, --bool, 0 userul nu a modificat programul, 1 da
    CONSTRAINT fk_utilizator_program FOREIGN KEY (USER_ID) REFERENCES UTILIZATORI(ID)
);

CREATE TABLE COMPETENTE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    DENUMIRE VARCHAR2(100) NOT NULL,
    ORE_ESTIMATE INTEGER,
    ORE_STUDIATE INTEGER DEFAULT 0,
    CONSTRAINT fk_utilizator_competente FOREIGN KEY (USER_ID) REFERENCES UTILIZATORI(ID)
);

COMMIT;